/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package stockmanagementsys;

/**
 *
 * @author HP EliteBook 840
 */
public class Barang extends javax.swing.JFrame {

    /** Creates new form Barang */
    public Barang() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Barangin = new javax.swing.JTextField();
        Jenisin = new javax.swing.JTextField();
        Barcodein = new javax.swing.JTextField();
        Hargain = new javax.swing.JTextField();
        Stokin = new javax.swing.JTextField();
        jTambah = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablebarang = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jHome = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("BARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setText("Nama Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 68, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText("Jenis");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 108, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setText("Barcode");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 148, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setText("Harga");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 191, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel6.setText("Exp");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 236, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel7.setText("Stok");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 280, -1, -1));
        getContentPane().add(Barangin, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 71, 229, -1));
        getContentPane().add(Jenisin, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 111, 229, -1));
        getContentPane().add(Barcodein, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 151, 229, -1));
        getContentPane().add(Hargain, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 194, 120, 30));
        getContentPane().add(Stokin, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 283, 100, -1));

        jTambah.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTambah.setText("Tambah");
        getContentPane().add(jTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 68, -1, -1));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setText("Edit");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 124, 89, -1));

        jHapus.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jHapus.setText("Hapus");
        getContentPane().add(jHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 188, 89, -1));

        jReset.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jReset.setText("Reset");
        getContentPane().add(jReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 246, 89, -1));

        Tablebarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Jenis", "Barcode", "Harga", "Exp", "Stok"
            }
        ));
        jScrollPane1.setViewportView(Tablebarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 353, 809, 245));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 110, 20));

        jHome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jHome.setText("Home");
        jHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHomeMouseClicked(evt);
            }
        });
        getContentPane().add(jHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 615, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockmanagementsys/pexels-johannes-plenio-1103970.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeMouseClicked
        dispose();
        Home home = new Home();
        home.show();
    }//GEN-LAST:event_jHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Barangin;
    private javax.swing.JTextField Barcodein;
    private javax.swing.JTextField Hargain;
    private javax.swing.JTextField Jenisin;
    private javax.swing.JTextField Stokin;
    private javax.swing.JTable Tablebarang;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JButton jHapus;
    private javax.swing.JButton jHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jTambah;
    // End of variables declaration//GEN-END:variables

}
