/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmanagementsys;

/**
 *
 * @author HP EliteBook 840
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form UserAccount
     */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jEdit = new javax.swing.JButton();
        jTambah = new javax.swing.JButton();
        Userinput = new javax.swing.JTextField();
        Passinput = new javax.swing.JTextField();
        Fullinput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tableusser = new javax.swing.JTable();
        jReset = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("USER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 132, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setText("Nama Lengkap");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 200, -1, -1));

        jEdit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jEdit.setText("Edit");
        getContentPane().add(jEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 132, 89, -1));

        jTambah.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTambah.setText("Tambah");
        jTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTambahMouseEntered(evt);
            }
        });
        jTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTambahActionPerformed(evt);
            }
        });
        getContentPane().add(jTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 67, -1, -1));

        Userinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserinputActionPerformed(evt);
            }
        });
        getContentPane().add(Userinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 73, 230, -1));

        Passinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassinputActionPerformed(evt);
            }
        });
        getContentPane().add(Passinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 138, 230, -1));
        getContentPane().add(Fullinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 203, 230, -1));

        Tableusser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Nama Lengkap"
            }
        ));
        jScrollPane1.setViewportView(Tableusser);
        if (Tableusser.getColumnModel().getColumnCount() > 0) {
            Tableusser.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 304, 814, 210));

        jReset.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jReset.setText("Reset");
        getContentPane().add(jReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 256, 89, -1));

        jHapus.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jHapus.setText("Hapus");
        getContentPane().add(jHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 197, 89, -1));

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setText("Home");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockmanagementsys/pexels-johannes-plenio-1103970.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 880, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PassinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassinputActionPerformed

    private void UserinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserinputActionPerformed

    private void jTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTambahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTambahMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTambahMouseEntered

    private void jTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTambahMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTambahMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        dispose();
        Home home = new Home();
        home.show();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fullinput;
    private javax.swing.JTextField Passinput;
    private javax.swing.JTable Tableusser;
    private javax.swing.JTextField Userinput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jEdit;
    private javax.swing.JButton jHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jTambah;
    // End of variables declaration//GEN-END:variables
}
