/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmanagementsys;

/**
 *
 * @author HP EliteBook 840
 */
public class Vendor extends javax.swing.JFrame {

    /**
     * Creates new form Vendor
     */
    public Vendor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Vendorinput = new javax.swing.JTextField();
        Emailinput = new javax.swing.JTextField();
        Noinput = new javax.swing.JTextField();
        Dressinput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablevendor = new javax.swing.JTable();
        jTambah = new javax.swing.JButton();
        jEdit = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jHome = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("VENDOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setText("Nama Vendor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 91, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 138, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel4.setText("No. Telp");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 186, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 232, -1, -1));
        getContentPane().add(Vendorinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 94, 241, -1));
        getContentPane().add(Emailinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 141, 241, -1));
        getContentPane().add(Noinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 192, 241, -1));
        getContentPane().add(Dressinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 235, 241, -1));

        Tablevendor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Vendor", "Email", "No. Telp", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(Tablevendor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 288, 820, 297));

        jTambah.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTambah.setText("Tambah");
        getContentPane().add(jTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 88, -1, -1));

        jEdit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jEdit.setText("Edit");
        getContentPane().add(jEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 135, 89, -1));

        jHapus.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jHapus.setText("Hapus");
        getContentPane().add(jHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 186, 89, -1));

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setText("Reset");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 241, 89, -1));

        jHome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jHome.setText("Home");
        jHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHomeMouseClicked(evt);
            }
        });
        getContentPane().add(jHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 603, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockmanagementsys/pexels-johannes-plenio-1103970.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeMouseClicked
        dispose();
        Home home = new Home();
        home.show();
    }//GEN-LAST:event_jHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dressinput;
    private javax.swing.JTextField Emailinput;
    private javax.swing.JTextField Noinput;
    private javax.swing.JTable Tablevendor;
    private javax.swing.JTextField Vendorinput;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jEdit;
    private javax.swing.JButton jHapus;
    private javax.swing.JButton jHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jTambah;
    // End of variables declaration//GEN-END:variables
}
